name: Program Code Convention Check

on:
  push:
    branches: [ main, laboratorywork-4 ]
  pull_request:
    branches: [ main, laboratorywork-4 ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install ESLint
        run: |
          npm install eslint --global
          eslint --version

      - name: Run ESLint check
        run: |
          eslint 2-SoftwareDesign/2.6-GitHubActions/ProgramCode.js || exit 0
