name: JavaScript Code Linter

on:
  push:
    branches: [ main, laboratorywork-4 ]

jobs:
  JavaScriptCodeLinter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code in Repository
        uses: actions/checkout@v3

      - name: Install JSON Linter Biome
        run: |
          npm install --save-dev --save-exact @biomejs/biome

      - name: Validate all JS files
        run: |
          npx @biomejs/biome check 2-SoftwareDesign/2.6-GitHubActions/ProgramCode.js


